### ISSUE TITLE
v2.10.13 appears to have lost getdate.tab.c during merge request

### ISSUE THREAD

**Issue by bkylerussell** [PeteDavidson/ptlib#1]
I think the following merge commit lost the addition of the bison-2.7 generated getdate.tab.c.

b3eda3c Merge branch 'master' into VerizonCert

After this merge, src/ptlib/common/getdate.tab.c no longer exists, which was added (see 2327da8 Add getdate.tab.c so that bison is not required when building.  This is because current bison 3.0 yields an error...) to allowing compiling ptlib on systems where bison 3.0 is installed.

Was this intentional?  Or is there an alternative approach that's now recommended instead of having getdate.tab.c checked in?

**Comment by PeteDavidson** [comment]
Added your changes, plus a change to have make clean not delete getdate.tab.c.
